### PR TITLE
Document A77 - Generation Outages

### PR DESCRIPTION
**Pull request by shatteringlass**
I got this working all in one afternoon. It's not very clean and need refactoring, but it gave me the data I needed so I thought I'd submit a PR.

### CODE REVIEW

**Comment by JrtPec** [comment]
Great! Thanks for your contribution, I'll try to find some time soon to review it and get it ready for a merge.
Important note though: Never, ever, commit API keys or credentials. In this case we're working with a free service so there's no harm, but still.

**Comment by shatteringlass** [comment]
Erm...it's great to help. 
I'm not really a professional programmer but I love python and data manipulation, and would very much like to become one.

I totally get your point regarding api keys, and I was surprised to find an api key in the settings file from the original repo! I actually left it untouched (even if locally I used my own key), but I figure I'd better remove that altogether.

**Comment by JrtPec** [comment]
My god, you're right. Looks like I forgot to follow my own advice 🤦‍♂️

**Comment by JrtPec** [comment]
cleaned it up a little bit.

- Replaced `domain` with `country_code`. So you can use the abbreviated version. Mappings can be found in `mappings.py`.
- Made the `docstatus` argument optional, which meant I had to move it around

**Comment by JrtPec** [comment]
I noticed that this means we're not done yet - all those Italian domains should be added to `mappings.py`.

**Pull request merged**
