### PR TITLE
Fixing the issue #234: documents_limited decorator removes data after concatenating by removing "duplicates"

### PR DESCRIPTION
**Pull request by carstenblank**
The issue #234 explains a problem that the merging on the decorators has been buggy and should be fixed.

This PR proposes one solution and creates a unit test that fails when the old code is used, and succeeds when the new code is used.

Please let me know together with issue #234 needs more explaination.

### CODE REVIEW

**Comment by Darrrian** [comment]
Hi, I've encountered the problem too, it breaks probably most functions that try to obtain multiple columns for a longer data period. The problem, I believe, is not in Entsoe sending any problematic data, but that the function, when limited, only gets part of the results, and in the concatenation itself adds the NAs.
Simple solution is not to drop added NAs:
```            
# df has multiined -> converted into two variable name columns
[74]melt_index_names = ['index', 'variable_0', 'variable_1']
# melt df to move each entry to unique row, then drop nas
[75]df = df.reset_index().melt('index').dropna()
# reformat the df back into original shape
[76]df = df.set_index(melt_index_names)['value'].unstack([-2, -1])
```
Your solution works well (the same), but I think it adresses issue that is not there :) (given the warning you show)

I didn't actually notice your code before I wrote this, it probably doesn't matter which is used, I expect that groupby would be slower, but I do not know. This approach seems safer, as it does not assume how method .median handles NAs.

**Comment by Darrrian** [comment]
I have given it a second thought and I think there is a problem in your solution. If entsoe would actually return 2 different values for 1 hour, median would probably not be correct. It would just mean some data issue on entsoe side - and thus error should be raised. Thus I think that outlined solution should be preffered, and maybe check for duplicit values should be added.
Best regards :)

**Comment by m-ganko** [comment]
It might be working for `query_contracted_reserve_prices`, but it is going to break other methods (which btw. are also broken due to this duplicates drop). For example `query_unavailability_...`, there are multiple `<timeInterval` rows and duplicates drop is causing wrong end date.

**Comment by fboerman** [comment]
hi I never really used this endpoint and dont fully understand what is going on. could you perhaps explain in a bit more details what is going wrong and how this fixes it?

@Darrrian what do you mean that more functions are broken? could you name an example? 

many thanks for the investigation so far!

**Comment by awarsewa** [comment]
Hi,
maybe I can help out here (at least with the data points I had the same Issue with).
Data for unavailability of generation and production is often submitted per unit of a plant with the same time stamp for each unit. This leads to the decorators @year_limited and @document_limited removing all but one of these entries since they are considered duplicates. Changing the decorators so that they check for actual "row duplicates" instead of just looking at the timestamp should fix this. Not sure about the other data points.

**Comment by pee-po** [comment]
Duplicated indices also happen for "corrected" data. I.e. Explicit Allocations - Long term / Medium term; CTA|UA-IPS > CTA|PL; there are two entries for late July: 01.07.2023 - 01.08.2023 and  17.07.2023 - 01.08.2023. This is due to an additional auction for this period (see [here](https://www.pse.pl/web/pse-eng/cross-border-electricity-exchange/auction-office/rzeszow-chmielnicka-interconnection/auction-announcements)). Contrary to the suggestion of @Darrrian this is not an error, nor a fluke - corrections happen.

The reason for de-duplication happening in `_limited` decorators is probably that partial matching and closed intervals would duplicate entries (@fboerman , correct me if I'm wrong - you seem to have made changes to this code). This is indicated by the fact that only `_limited` decorators assume this approach. But there are more reasons for duplicate time indices and blanket duplicate dropping is harmful. This PR also doesn't address the example above. 

My idea would be to address the problem at its source. If the reason for de-duplication is partial matching and closed intervals overlap, then the solution is to properly trim the indices based on `start` and `stop` (which would leave duplicates) or to de-duplicate on a more relevant criterion (so that there are no duplicates and only - say - most recent data are returned).

We may have to take a page from DB developers and either extend the index with record's version number (or a relevant tech date) or compute it in the background and drop based on it.

**Comment by fboerman** [comment]
hi @pee-po sorry for the late reply was a bit busy. Thanks for the thorough explanation, trimming seems like a good idea. Would you be willing to make a PR for that?

**Comment by fboerman** [comment]
@pee-po  thanks! will await your PR then to work on it further

**Comment by fboerman** [comment]
lets move the discussion to the new PR #287

**Pull request closed without merging**
