### PR TITLE
Aggregated bids

### PR DESCRIPTION
**Pull request by LiInGit**
added aggregated_bids
see
https://transparency.entsoe.eu/balancing/r2/aggregatedBids/show

### CODE REVIEW

**Comment by amandasb** [comment]
Is this branch going to be merged to master anytime soon?

**Comment by fboerman** [comment]
hi @amandasb ! sorry for the late response was a bit busy. Thanks for taking the time to create this PR! I have two remarks:
- do you have a practical example I can test with your fork to see what it does?
- you seem to have adjusted also the decorator which is used in many functions. Please explain why you did this and split it off in a seperate PR since it has nothing to do with this new feature. Then we can better discuss that there.

Thanks!

**Comment by amandasb** [comment]
Hi @fboerman. It's not me who has created this PR, but I want to use the aggregated bids functionality. Maybe @LiInGit can answer your questions?

**Comment by awarsewa** [comment]
Hi @fboerman,
sorry, @LiInGit and me are still inexperienced with open source projects. 
I apologize for the confusion.

Currently, this fork adds two more data points of ETP:
- [Aggregated Bids](https://transparency.entsoe.eu/balancing/r2/aggregatedBids/show) from Balancing
- [Prices of Activated Balancing Energy](https://transparency.entsoe.eu/balancing/r3/pricesOfActivatedBalancingEnergy/show)
The latter was mainly added for the MARI Cross Border Marginal Price. mappings.py had to be modified to include the Bidding Zone AMP_LU for this.

The change to the decorator was made to resolve the issue of the decorators deleting data points with identical timestamps. For some time series, it is perfectly valid to have identical timestamps (e.g. Unavailability of Generation etc.) so we opted to drop duplicate rows instead of rows with identical timestamps. This way, no information is lost.

If you prefer separate PRs we'll spilt this into three different ones.

**Comment by fboerman** [comment]
hi @awarsewa no worries!

 ah okay that duplication issue is currently being discussed seperately in pullrequest #234  and a better solution is proposed in the comments. I would therefor like to ask you to remove your changes to the decorator? adding an extra query is always great to merge but the decorator needs some extra thought. Thanks!

**Comment by awarsewa** [comment]
Hi @fboerman ,

done, thanks. Less work for me like this.

**Comment by fboerman** [comment]
very nice @awarsewa , do you have a code snippit which returns actual data for me to quick tests? Then its easier for me to do a quick check and dont have to hunt for which zone does publish this data haha

**Comment by awarsewa** [comment]
```Python
from entsoe import EntsoePandasClient
import os
import pandas as pd

api_key = os.environ.get('ENTSOE_API_KEY')
start = pd.Timestamp(2023,9,1, tz='Europe/Brussels')
end = pd.Timestamp(2023,9,1,23,59,59, tz='Europe/Brussels')

client = EntsoePandasClient(api_key=api_key)
aggregated_bids = client.query_aggregated_bids("10YDE-ENBW-----N", process_type="A51", start=start, end=end)
cbmp = client.query_activated_balancing_energy_prices("DE_AMP_LU", start=start, end=end, process_type="A60", business_type="A97")
```

**Comment by fboerman** [comment]
great many thanks @awarsewa ! have merged it and will push out a release together with some other things

**Pull request merged**
