### PR TITLE
Resolve #292

### LINKED ISSUE #292: Queries using the `EntsoePandasClient` expecting yearly data return empty dataframes
I believe a recent change is breaking queries returning yearly data like `client.query_installed_generation_capacity(country_code, start, end, psr_type=None)`

example to recreate issue:
```python
from entsoe import EntsoePandasClient
import pandas as pd


client = EntsoePandasClient(api_key=API_KEY)

start = pd.Timestamp('20171201', tz='Europe/Brussels')
end = pd.Timestamp('20180101', tz='Europe/Brussels')
country_code = "BE"

client.query_installed_generation_capacity(
    country_code=country_code, start=start, end=end, psr_type="B01"
)
```

Expected result:
```
  Biomass
2017-01-01 00:00:00+01:00    598.0
```

Returned results:
```
Empty DataFrame
Columns: [Biomass]
Index: []
```

_Originally posted by @badrbmb in https://github.com/EnergieID/entsoe-py/pull/287#discussion_r1456458012_

### PR DESCRIPTION
**Pull request by pee-po**
This is a followup to #287 due to #292.

This PR fixes a faulty assumption in (recently reworked) `yearly_limited` decorator - that the start timestamp will be found in frame index. Now the special case for the first interval is more explicit.

Sorry for the trouble!

### CODE REVIEW

**Comment by pee-po** [comment]
@badrbmb sorry for the trouble - I think this should fix the problem. You can build from my branch and test it yourself - I'm sure it will be helpful for the maintainers.

**Comment by fboerman** [comment]
hi @pee-po and @badrbmb thanks for looking into this and providing a fix! @badrbmb could you check if this solution works? Then I will merge this.

**Comment by badrbmb** [comment]
Thanks for the fix @pee-po. Tested locally and works like a charm 💯

**Comment by fboerman** [comment]
many thanks guys!

**Pull request merged**
